version: '2'

#volumes:
#  dbdata:

#networks:
#  db_nw:
#    driver: bridge

services:
  web:
    build: .
    ports:
     - 8000:8000
    volumes:
     - .:/usr/src/application
    depends_on:
     - db
     - redis
    env_file:
      - env_vars
    links:
      - db:database
      - redis

  redis:
    image: redis:alpine

  db:
    container_name: database
    hostname: database
    image: postgres:9.6.5
    ports:
      - 5432:5432
    env_file:
      - env_vars
    volumes:
      - ./data/postgres:/var/lib/postgresql/data